In [25]:
import zipfile
import os
import cv2

zip_path = "/content/archive.zip"
extract_path = "extracted_images"

# Extract the ZIP file
with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

# Read all images
images = []

for root, dirs, files in os.walk(extract_path):
    for file in files:
        if file.lower().endswith((".jpg", ".jpeg", ".png", ".bmp")):
            img_path = os.path.join(root, file)
            img = cv2.imread(img_path)

            if img is not None:
                images.append(img)

print("Total images loaded:", len(images))

Total images loaded: 813


In [26]:
images= images[:100]
print("Total images selected:",len(images))

Total images selected: 100


In [27]:
from PIL import Image,ImageEnhance,ImageOps
import pandas as pd
image_info=[]

In [28]:
for i,img in enumerate(images):
  height,width,channels=img.shape
  image_info.append([i+1,height,width,channels])
df=pd.DataFrame(image_info,columns=['Image_No','Height','Width','Channels'])
print(df)

    Image_No  Height  Width  Channels
0          1     128    128         3
1          2     128    128         3
2          3     128    128         3
3          4     128    128         3
4          5     128    128         3
..       ...     ...    ...       ...
95        96     128    128         3
96        97     128    128         3
97        98     128    128         3
98        99     128    128         3
99       100     128    128         3

[100 rows x 4 columns]


In [29]:
resized_images=[]
for img in images:
  resized_img=cv2.resize(img,(224,224))
  resized_images.append(resized_img)

In [30]:
normalized_images=[]
for img in resized_images:
  normalized_img=img/255.0
  normalized_images.append(normalized_img)
print(len(normalized_images))

100


In [31]:
from cv2 import cvtColor,COLOR_BGR2GRAY
grayscale_images=[]
for img in resized_images:
  grayscale_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  grayscale_images.append(grayscale_img)
print(len(grayscale_images))
grayscale_images

100


[array([[136, 136, 136, ..., 122, 124, 124],
        [134, 135, 135, ..., 121, 122, 123],
        [132, 132, 134, ..., 119, 120, 120],
        ...,
        [122, 119, 114, ..., 163, 163, 162],
        [120, 117, 113, ..., 162, 160, 158],
        [118, 116, 112, ..., 161, 158, 156]], dtype=uint8),
 array([[154, 144, 129, ..., 101,  91,  84],
        [129, 120, 105, ...,  98,  87,  80],
        [ 90,  81,  68, ...,  93,  81,  73],
        ...,
        [ 97, 125, 169, ..., 119, 144, 160],
        [115, 133, 162, ..., 136, 153, 164],
        [126, 139, 158, ..., 147, 158, 166]], dtype=uint8),
 array([[ 82,  89, 101, ..., 114,  97,  87],
        [ 95, 101, 109, ..., 115, 100,  91],
        [116, 118, 121, ..., 117, 105,  97],
        ...,
        [ 44,  39,  30, ...,   4,  11,  16],
        [ 40,  36,  29, ...,   6,  14,  21],
        [ 37,  34,  28, ...,   7,  17,  24]], dtype=uint8),
 array([[13, 13, 13, ..., 11, 11, 11],
        [13, 13, 13, ..., 11, 11, 11],
        [13, 13, 13, ..., 11

In [32]:
from cv2 import cvtColor,COLOR_BGR2GRAY
rgb_images=[]
for img in resized_images:
  rgb_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  rgb_images.append(rgb_img)
print(len(rgb_images))

100


In [33]:
hsv_images=[]
for img in resized_images:
  hsv_img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
  hsv_images.append(hsv_img)
print(len(hsv_images))

100


In [34]:
normalized_images

[array([[[0.43921569, 0.5372549 , 0.55686275],
         [0.44705882, 0.5372549 , 0.55686275],
         [0.4627451 , 0.5372549 , 0.55686275],
         ...,
         [0.11372549, 0.59607843, 0.38431373],
         [0.11372549, 0.60392157, 0.39215686],
         [0.11372549, 0.60784314, 0.39607843]],
 
        [[0.43529412, 0.53333333, 0.54901961],
         [0.44313725, 0.53333333, 0.54901961],
         [0.4627451 , 0.53333333, 0.55294118],
         ...,
         [0.10980392, 0.59215686, 0.38039216],
         [0.10980392, 0.6       , 0.38431373],
         [0.10980392, 0.60392157, 0.38431373]],
 
        [[0.42352941, 0.5254902 , 0.53333333],
         [0.43921569, 0.5254902 , 0.5372549 ],
         [0.4627451 , 0.5254902 , 0.54509804],
         ...,
         [0.10980392, 0.58823529, 0.36862745],
         [0.10980392, 0.59215686, 0.36862745],
         [0.10980392, 0.59607843, 0.36470588]],
 
        ...,
 
        [[0.38039216, 0.49411765, 0.49019608],
         [0.38039216, 0.4745098 , 0.48627

In [35]:
import os

# Create a directory for augmented images
augmented_dir = "augmented_images"
#Creates the directory augmented_images
os.makedirs(augmented_dir, exist_ok=True)
def augment_image(image, image_id):
    image=Image.fromarray(cv2.cvtColor(image,cv2.COLOR_BGR2RGB))
    flipped = ImageOps.mirror(image)
    flipped.save(os.path.join(augmented_dir,f"flipped_{image_id}.png"))


    rotated = image.rotate(30)
    rotated.save(os.path.join(augmented_dir,f"rotated_{image_id}.png"))

    enhancer = ImageEnhance.Brightness(image)
    brighter = enhancer.enhance(1.5)
    brighter.save(os.path.join(augmented_dir,f"brighter_{image_id}.png"))

    w,h=image.size
    zoomed=image.crop((w*0.1,h*0.1,w*0.9,h*0.9))
    zoomed=zoomed.resize((w,h))
    zoomed.save(os.path.join(augmented_dir,f"zoomed_{image_id}.png"))

for i,img in enumerate(resized_images):
  augment_image(img,i)
print("Augmented completed")

Augmented completed


In [ ]:
import cv2
import numpy as np

def preprocess_image(img):

    # Resize
    img = cv2.resize(img, (224, 224))

    # RGB Conversion
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

    # Normalization
    img = img / 255.0

    return img

# Apply preprocessing to all images
processed_images = []

for img in images:
    processed_images.append(preprocess_image(img))

print("Total processed images:", len(processed_images))